apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: EurekaServer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: EurekaServer
    spec:
      containers:
        - name: EurekaServer
          image: EurekaServer:20190421
          ports:
            - containerPort: 8671
              protocol: TCP