
spring:
  application:
    name:eureka
#端口号
server:
  port: 8671
#Eureka实例名，集群中根据这里相互识别
eureka:
  instance:
    hostname: localhost
  #客户端
  client:
    #是否开启注册服务，因为这里如果为true表示自己注册自己，而自己就是一个服务注册方，没必要自己注册自己
    register-with-eureka: false
    #是否拉取服务列表，这里我只提供服务给别的服务。
    fetch-registry: false
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8672/eureka/
      #defaultZone: http://192.168.1.11:8672/eureka/,http://192.168.1.10:8671/eureka/